import { motion } from "framer-motion";

import {  Bot,  Sparkles,} from "lucide-react";

function AIResponseCard({
  title = "AI Response",
  content = "",
}) {

  return (
    <motion.div
      initial={{
        opacity: 0,
        y: 30,
      }}
      animate={{
        opacity: 1,
        y: 0,
      }}
      transition={{
        duration: 0.5,
      }}
      className="
        relative
        glass
        rounded-3xl
        overflow-hidden
        border
        border-white/10
      "
    >

      <div
        className="
          absolute
          top-0
          right-0
          w-44
          h-44
          bg-cyan-500/10
          rounded-full
          blur-3xl
        "
      />

      <div
        className="
          relative
          z-10
          flex
          items-center
          gap-4
          px-6
          py-5
          border-b
          border-white/10
          bg-black/20
        "
      >

        <div
          className="
            w-14
            h-14
            rounded-3xl
            bg-gradient-to-r
            from-cyan-500
            to-violet-500
            flex
            items-center
            justify-center
            glow
          "
        >

          <Bot size={26} />

        </div>

        <div>

          <h2
            className="
              text-2xl
              font-black
            "
          >
            {title}
          </h2>

          <p className="text-gray-400">
            Generated by DevSphere AI
          </p>

        </div>

        <div className="ml-auto">

          <Sparkles
            size={24}
            className="text-cyan-400"
          />

        </div>

      </div>

      <div
        className="
          relative
          z-10
          p-6
        "
      >

        <p
          className="
            text-gray-300
            leading-relaxed
            whitespace-pre-wrap
          "
        >
          {content}
        </p>

      </div>

    </motion.div>
  );
}

export default AIResponseCard;